### ISSUE TITLE
Default recipe is broken

### ISSUE THREAD

**Issue by rafaduran** [edelight/chef-mongodb#46]
Right now default recipe is broken, at least on Ubuntu, Debian and CentOS (FreeBSD should work, but i couldn't test it):

```
[Sun, 19 Aug 2012 09:41:13 +0200] ERROR: Running exception handlers
[Sun, 19 Aug 2012 09:41:13 +0200] ERROR: Exception handlers complete
[Sun, 19 Aug 2012 09:41:13 +0200] FATAL: Stacktrace dumped to /tmp/vagrant-chef-1/chef-stacktrace.out
[Sun, 19 Aug 2012 09:41:13 +0200] FATAL: Chef::Exceptions::Package: package[mongo-10gen-server] (mongodb::default line 22) had an error: Chef::Exceptions::Package: No version specified, and no candidate version available for mongo-10gen-server
```

I think the issue comes from SHA: e0f2c79ff4736f8e68c14431a76696b49a95df72, where default package name was changed to 'mongodb-10gen-server' and 10gen repository isn't added by default recipe.

**Comment by rafaduran** [comment]
I think old default 'mongodb' should work ok, and wherever the 10gen repository is installed we can do something like:

```
node.set[:mongodb][:package_name] = 'mongodb-10gen-server'
```

**Comment by jamesonjlee** [comment]
This brings up a good point, should we by default add the 10gen repo whenever possible?

cc @dcrosta @miketheman

**Comment by dcrosta** [comment]
I would say yes.

**Comment by miketheman** [comment]
For maximum flexibility, we should provide a recipe for package install, and another for non-package that sets up inits, etc.
See the nginx cookbook for how they do it: https://github.com/opscode-cookbooks/nginx/blob/master/attributes/default.rb#L69

**Comment by dcrosta** [comment]
I agree, but I think we should defer that until the future. Let's make sure this cookbook works well for the platforms it currently supports first. 

For this particular issue, there's a simple fix: default the package name to "mongodb" (as it had been before #11), and change that in the `case` in 10gen_repo

**Comment by gamafranco** [comment]
+1

**Comment by josh-at-knoesis** [comment]
+1

**Comment by tlfbrito** [comment]
+1

**Comment by gianarb** [comment]
Sorry but i don't understand, I'm trying to install mongo with this cookbook in a CentOS, but I'm trying different version `2.4.5`, `2.2.1`, `nil`
but return 
`Chef::Exceptions::Package: package[mongo-10gen-server] (mongodb::default line 22) had an error: Chef::Exceptions::Package: Version 2.4.5 of mongo-10gen-server not found. Did you specify both version and release? (version-release, e.g. 1.84-10.fc6)`
Into a Debian VM `2.4.5` runs

What is a good version? 
Thanks!

**Comment by josephholsten** [comment]
I don't know how to make it work without the 10gen repo. We should probably make this work better out of the box, or at least VERY EXPLICITLY MENTION IT AT THE TOP OF THE DOCS. But obviously, a less shouty solution would be preferable. 

## 

http://josephholsten.com

**Comment by gianarb** [comment]
@josephholsten thanks for this response, but this morning I'm trying to use 10 gen repo, my configuration (use Vagrant) is 

```
add_recipe "mongodb::10gen_repo"
add_recipe "mongodb"
chef.json = {
        :mongodb => {
            :package_version => "2.4.0"
        }
}
```

In a Debian system this configuration works, have someone installed this cookbooks in a CentOs? I use CentOS 6.4  X64 of [Opscode/Bento](https://github.com/opscode/bento). But this is my error.. 

``` sh
================================================================================
Error executing action `install` on resource 'package[mongo-10gen-server]'
================================================================================


Chef::Exceptions::Package
-------------------------
Version 2.4.0 of mongo-10gen-server not found. Did you specify both version and release? (version-release, e.g. 1.84-10.fc6)


Resource Declaration:
---------------------
# In /tmp/vagrant-chef-1/chef-solo-1/cookbooks/mongodb/recipes/default.rb

 22: package node[:mongodb][:package_name] do
 23:   action :install
 24:   version node[:mongodb][:package_version]
 25: end
 26: 



Compiled Resource:
------------------
# Declared in /tmp/vagrant-chef-1/chef-solo-1/cookbooks/mongodb/recipes/default.rb:22:in `from_file'

package("mongo-10gen-server") do
  action [:install]
  retries 0
  retry_delay 2
  package_name "mongo-10gen-server"
  version "2.4.0"
  cookbook_name :mongodb
  recipe_name "default"
end
```

**Comment by jamesonjlee** [comment]
now fixed in 0.14.0

**Comment by gianarb** [comment]
:+1: Thanks!

**Comment by ringular** [comment]
Hey @GianArb, @jamesonjlee i'm still having this issue on `0.14.0` & `1.14.3`
Is this fix confirmed working for you?

My runlist is:

```
"recipe[mongodb::10gen_repo]",
"recipe[mongodb::default]"
```

Here's my log:

```
Recipe: mongodb::install
  * file[/etc/sysconfig/mongodb] action create_if_missing (up to date)
  * template[/etc/mongodb.conf] action create_if_missing (up to date)
  * template[/etc/init.d/mongod] action create_if_missing (up to date)
  * package[mongo-10gen-server] action install
================================================================================
Error executing action `install` on resource 'package[mongo-10gen-server]'
================================================================================


Chef::Exceptions::Package
-------------------------
Version 2.4.6 of mongo-10gen-server not found. Did you specify both version and release? (version-release, e.g. 1.84-10.fc6)


Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/mongodb/recipes/install.rb

 51: package node[:mongodb][:package_name] do
 52:     options packager_opts
 53:     action :install
 54:     version node[:mongodb][:package_version]
 55: end



Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/mongodb/recipes/install.rb:51:in `from_file'

package("mongo-10gen-server") do
  action [:install]
  retries 0
  retry_delay 2
  package_name "mongo-10gen-server"
  version "2.4.6"
  cookbook_name "mongodb"
  recipe_name "install"
end



[2013-12-26T08:25:17+00:00] ERROR: Running exception handlers
[2013-12-26T08:25:17+00:00] ERROR: Exception handlers complete
[2013-12-26T08:25:17+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 5 resources updated
[2013-12-26T08:25:17+00:00] ERROR: package[mongo-10gen-server] (mongodb::install line 51) had an error: Chef::Exceptions::Package: Version 2.4.6 of mongo-10gen-server not found. Did you specify both version and release? (version-release, e.g. 1.84-10.fc6)
[2013-12-26T08:25:17+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by ringular** [comment]
And to add, if i specify my version to be `2.6.1-mongodb_1` instead of `2.4.6` 
I get this:

```
Recipe: mongodb::10gen_repo
  * yum_repository[10gen] action addRecipe: <Dynamically Defined Resource>
  * template[/etc/yum.repos.d/10gen.repo] action create (up to date)
  * execute[yum-makecache-10gen] action nothing (skipped due to action :nothing)
  * ruby_block[yum-cache-reload-10gen] action nothing (skipped due to action :nothing)
 (up to date)
Recipe: mongodb::install
  * file[/etc/sysconfig/mongodb] action create_if_missing (up to date)
  * template[/etc/mongodb.conf] action create_if_missing (up to date)
  * template[/etc/init.d/mongod] action create_if_missing (up to date)
  * package[mongo-10gen-server] action install
================================================================================
Error executing action `install` on resource 'package[mongo-10gen-server]'
================================================================================


Chef::Exceptions::Exec
----------------------
 returned 1, expected 0


Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/mongodb/recipes/install.rb

 51: package node[:mongodb][:package_name] do
 52:     options packager_opts
 53:     action :install
 54:     version node[:mongodb][:package_version]
 55: end



Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/mongodb/recipes/install.rb:51:in `from_file'

package("mongo-10gen-server") do
  action [:install]
  retries 0
  retry_delay 2
  package_name "mongo-10gen-server"
  version "2.4.6-mongodb_1"
  cookbook_name "mongodb"
  recipe_name "install"
end



[2013-12-26T08:34:49+00:00] ERROR: Running exception handlers
[2013-12-26T08:34:49+00:00] ERROR: Exception handlers complete
[2013-12-26T08:34:49+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 5 resources updated
[2013-12-26T08:34:50+00:00] ERROR: package[mongo-10gen-server] (mongodb::install line 51) had an error: Chef::Exceptions::Exec:  returned 1, expected 0
[2013-12-26T08:34:51+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

```

**Comment by jamesonjlee** [comment]
@ringular can you try with latest master? also what distribution are you on?

**Comment by ringular** [comment]
hey @jamesonjlee 
I just managed to figure it out. turns out the issue is with 10gen returning unsigned packages. I updated `recipe/default.rb` to

``` ruby
package node[:mongodb][:package_name] do
  action :install
  version node[:mongodb][:package_version]
  options "--nogpgcheck"
end
```

& it works now. Also updated `recipes/10gen_repo.rb` (though not necessary) to:

``` ruby
case node['platform_family']
when "debian", "ubuntu"
  include_recipe "apt"

  execute "apt-get update" do
    action :nothing
  end

  # Adds the repo: http://www.mongodb.org/display/DOCS/Ubuntu+and+Debian+packages
  apt_repository "10gen" do
    uri "http://downloads-distro.mongodb.org/repo/#{node[:mongodb][:apt_repo]}"
    distribution "dist"
    components ["10gen"]
    keyserver "hkp://keyserver.ubuntu.com:80"
    key "7F0CEB10"
    action :add
    notifies :run, "execute[apt-get update]", :immediately
  end

when "rhel","fedora"
  include_recipe "yum"

  execute "yum clean all" do
    action :nothing
  end

  yum_repository "10gen" do
    description "10gen RPM Repository"
    url "http://downloads-distro.mongodb.org/repo/redhat/os/#{node['kernel']['machine']  =~ /x86_64/ ? 'x86_64' : 'i686'}"
    action :add
    notifies :run, "execute[yum clean all]", :immediately
  end

else
    Chef::Log.warn("Adding the #{node['platform_family']} 10gen repository is not yet not supported by this cookbook")
end
```

Also, to answer your question I'm on Amazon EC2 Linux

**Comment by jamesonjlee** [comment]
seems to be a known issue: https://jira.mongodb.org/browse/SERVER-8770
@ringular if you want to roll the --nopgpkey into a pr, I will add it in.

**Comment by ringular** [comment]
@jamesonjlee done!
